# Long Vs Wide Data

<img src = "wideLong.png" alt = "Wide vs Long table" width = "650">

<p>In pandas, data can be structured in either a long format or a wide format, each suitable for different analytical tasks.</p>

<h1>Wide Format:</h1>
<ol>
    <li><h3>Structure: </h3>Each row represents a unique observation, and different attributes or variables are stored in separate columns.</li>
    <li><h3>Characteristics:</h3>
        <ul>
            <li>More columns, fewer rows (relative to long format).</li>
            <li>Column headers often represent values or categories of a variable.</li>
            <li>Easier for human readability and direct analysis of individual attributes.</li>
        </ul>
    </li>
    <li><h3>Example: </h3>A dataset with each row representing a person, and columns for "Age", "Height", "Weight".</li>
</ol>

<h1>Long Format:</h1>
<ol>
    <li><h3>Structure: </h3>Each row represents a single observation of a specific attribute, with identifier columns to group related observations.</li>
    <li><h3>Characteristics:</h3>
        <ul>
            <li>Fewer columns, more rows (relative to wide format).</li>
            <li>Typically includes an "identifier" column, a "variable" column (naming the attribute), and a "value" column.</li>
            <li>More suitable for statistical analysis, plotting, and database storage.</li>
        </ul>
    </li>
    <li><h3>Example: </h3>A dataset with each row representing a measurement for a person (e.g., one row for "Person A, Age, 30", another for "Person A, Height, 175").</li>
</ol>

In [2]:
import numpy as np, pandas as pd

In [8]:
# melt (wide to long) --> simple example 
df1 = pd.DataFrame({'cs':[120]})
df1

    cs
0  120

In [9]:
df1.melt()

  variable  value
0       cs    120

In [11]:
df2 = pd.DataFrame({'cs' : [120], 'ds' : [170], 'ai' : [180]})
df2

    cs   ds   ai
0  120  170  180

In [12]:
df2.melt()

  variable  value
0       cs    120
1       ds    170
2       ai    180

In [13]:
df2.melt(var_name = 'dept', value_name = 'num_of_students')

  dept  num_of_students
0   cs              120
1   ds              170
2   ai              180

In [14]:
df3 = pd.DataFrame(
    {
        'branch' : ['cs', 'ai', 'ds', 'se'],
        '2020' : [110, 150, 130, 115],
        '2021' : [109, 160, 150, 115],
        '2022' : [110, 180, 160, 100],
        '2023' : [89, 180, 170, 95]
    }
)

df3

  branch  2020  2021  2022  2023
0     cs   110   109   110    89
1     ai   150   160   180   180
2     ds   130   150   160   170
3     se   115   115   100    95

In [15]:
df3.melt()

   variable value
0    branch    cs
1    branch    ai
2    branch    ds
3    branch    se
4      2020   110
5      2020   150
6      2020   130
7      2020   115
8      2021   109
9      2021   160
10     2021   150
11     2021   115
12     2022   110
13     2022   180
14     2022   160
15     2022   100
16     2023    89
17     2023   180
18     2023   170
19     2023    95

In [17]:
df3.melt(id_vars = ['branch'], var_name = 'Year', value_name = 'num_of_students')

   branch  Year  num_of_students
0      cs  2020              110
1      ai  2020              150
2      ds  2020              130
3      se  2020              115
4      cs  2021              109
5      ai  2021              160
6      ds  2021              150
7      se  2021              115
8      cs  2022              110
9      ai  2022              180
10     ds  2022              160
11     se  2022              100
12     cs  2023               89
13     ai  2023              180
14     ds  2023              170
15     se  2023               95

### Real Life Ecamples of Melt

In [23]:
confirm_cases = pd.read_csv(r'time_series_covid19_confirmed_global.csv')
confirm_cases.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095

In [42]:
death = pd.read_csv('time_series_covid19_deaths_global.csv')
death.sample(5)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
270,Gibraltar,United Kingdom,36.1408,-5.3536,0,0,0,0,0,0,...,110,110,110,110,110,110,110,110,110,110
107,NaN,Djibouti,11.8251,42.5903,0,0,0,0,0,0,...,189,189,189,189,189,189,189,189,189,189
26,NaN,Benin,9.3077,2.3158,0,0,0,0,0,0,...,163,163,163,163,163,163,163,163,163,163
126,Reunion,France,-21.1151,55.5364,0,0,0,0,0,0,...,906,906,906,906,906,906,906,906,906,906
212,NaN,Panama,8.5380,-80.7821,0,0,0,0,0,0,...,8554,8554,8554,8567,8567,8567,8567,8567,8567,8567

In [43]:
death = death.melt(id_vars = ['Province/State', 'Country/Region', 'Lat', 'Long'], var_name = 'date', value_name = 'num_of_death')
death

,Province/State,Country/Region,Lat,Long,date,num_of_death
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [44]:
death.head()

  Province/State Country/Region       Lat       Long     date  num_of_death
0            NaN    Afghanistan  33.93911  67.709953  1/22/20             0
1            NaN        Albania  41.15330  20.168300  1/22/20             0
2            NaN        Algeria  28.03390   1.659600  1/22/20             0
3            NaN        Andorra  42.50630   1.521800  1/22/20             0
4            NaN         Angola -11.20270  17.873900  1/22/20             0

In [38]:
confirm_cases = confirm.melt(id_vars = ['Province/State', 'Country/Region', 'Lat', 'Long'], var_name = 'date', value_name = 'num_of_cases')
confirm_cases

,Province/State,Country/Region,Lat,Long,date,num_of_cases
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981

In [45]:
confirm_cases.head()

  Province/State Country/Region       Lat       Long     date  num_of_cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20             0
1            NaN        Albania  41.15330  20.168300  1/22/20             0
2            NaN        Algeria  28.03390   1.659600  1/22/20             0
3            NaN        Andorra  42.50630   1.521800  1/22/20             0
4            NaN         Angola -11.20270  17.873900  1/22/20             0

In [47]:
covid_merge_data = confirm_cases.merge(death, on = ['Province/State', 'Country/Region', 'Lat',	'Long',	'date'])
covid_merge_data

,Province/State,Country/Region,Lat,Long,date,num_of_cases,num_of_death
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0,0
...,...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981,5637

In [48]:
covid_merge_data[['Country/Region', 'date', 'num_of_cases', 'num_of_death']]

              Country/Region     date  num_of_cases  num_of_death
0                Afghanistan  1/22/20             0             0
1                    Albania  1/22/20             0             0
2                    Algeria  1/22/20             0             0
3                    Andorra  1/22/20             0             0
4                     Angola  1/22/20             0             0
...                      ...      ...           ...           ...
311248    West Bank and Gaza   1/2/23        703228          5708
311249  Winter Olympics 2022   1/2/23           535             0
311250                 Yemen   1/2/23         11945          2159
311251                Zambia   1/2/23        334661          4024
311252              Zimbabwe   1/2/23        259981          5637

[311253 rows x 4 columns]