# Long Vs Wide Data

<img src = "wideLong.png" alt = "Wide vs Long table" width = "650">

<p>In pandas, data can be structured in either a long format or a wide format, each suitable for different analytical tasks.</p>

<h1>Wide Format:</h1>
<ol>
    <li><h3>Structure: </h3>Each row represents a unique observation, and different attributes or variables are stored in separate columns.</li>
    <li><h3>Characteristics:</h3>
        <ul>
            <li>More columns, fewer rows (relative to long format).</li>
            <li>Column headers often represent values or categories of a variable.</li>
            <li>Easier for human readability and direct analysis of individual attributes.</li>
        </ul>
    </li>
    <li><h3>Example: </h3>A dataset with each row representing a person, and columns for "Age", "Height", "Weight".</li>
</ol>

<h1>Long Format:</h1>
<ol>
    <li><h3>Structure: </h3>Each row represents a single observation of a specific attribute, with identifier columns to group related observations.</li>
    <li><h3>Characteristics:</h3>
        <ul>
            <li>Fewer columns, more rows (relative to wide format).</li>
            <li>Typically includes an "identifier" column, a "variable" column (naming the attribute), and a "value" column.</li>
            <li>More suitable for statistical analysis, plotting, and database storage.</li>
        </ul>
    </li>
    <li><h3>Example: </h3>A dataset with each row representing a measurement for a person (e.g., one row for "Person A, Age, 30", another for "Person A, Height, 175").</li>
</ol>

In [2]:
import numpy as np, pandas as pd

In [8]:
# melt (wide to long) --> simple example 
df1 = pd.DataFrame({'cs':[120]})
df1

    cs
0  120

In [9]:
df1.melt()

  variable  value
0       cs    120

In [11]:
df2 = pd.DataFrame({'cs' : [120], 'ds' : [170], 'ai' : [180]})
df2

    cs   ds   ai
0  120  170  180

In [12]:
df2.melt()

  variable  value
0       cs    120
1       ds    170
2       ai    180

In [13]:
df2.melt(var_name = 'dept', value_name = 'num_of_students')

  dept  num_of_students
0   cs              120
1   ds              170
2   ai              180

In [14]:
df3 = pd.DataFrame(
    {
        'branch' : ['cs', 'ai', 'ds', 'se'],
        '2020' : [110, 150, 130, 115],
        '2021' : [109, 160, 150, 115],
        '2022' : [110, 180, 160, 100],
        '2023' : [89, 180, 170, 95]
    }
)

df3

  branch  2020  2021  2022  2023
0     cs   110   109   110    89
1     ai   150   160   180   180
2     ds   130   150   160   170
3     se   115   115   100    95

In [15]:
df3.melt()

   variable value
0    branch    cs
1    branch    ai
2    branch    ds
3    branch    se
4      2020   110
5      2020   150
6      2020   130
7      2020   115
8      2021   109
9      2021   160
10     2021   150
11     2021   115
12     2022   110
13     2022   180
14     2022   160
15     2022   100
16     2023    89
17     2023   180
18     2023   170
19     2023    95

In [17]:
df3.melt(id_vars = ['branch'], var_name = 'Year', value_name = 'num_of_students')

   branch  Year  num_of_students
0      cs  2020              110
1      ai  2020              150
2      ds  2020              130
3      se  2020              115
4      cs  2021              109
5      ai  2021              160
6      ds  2021              150
7      se  2021              115
8      cs  2022              110
9      ai  2022              180
10     ds  2022              160
11     se  2022              100
12     cs  2023               89
13     ai  2023              180
14     ds  2023              170
15     se  2023               95