# Multi Index DataFrame

In [1]:
import numpy as np, pandas as pd

In [6]:
multiIndVal = [('cs',2012), ('cs', 2013), ('cs', 2014), ('ee', 2012), ('ee', 2013), ('ee', 2014), ('ee', 2015)]
multiInd = pd.MultiIndex.from_tuples(multiIndVal)

In [7]:
multi_df1 = pd.DataFrame(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [9, 10],
        [11, 12],
        [13, 14],
    ],
    index = multiInd,
    columns = ['avg_package', 'students']
)

multi_df1

         avg_package  students
cs 2012            1         2
   2013            3         4
   2014            5         6
ee 2012            7         8
   2013            9        10
   2014           11        12
   2015           13        14

In [9]:
multi_df1.loc['cs']
multi_df1.loc['ee']

      avg_package  students
2012            7         8
2013            9        10
2014           11        12
2015           13        14

In [10]:
multi_df1['avg_package']

cs  2012     1
    2013     3
    2014     5
ee  2012     7
    2013     9
    2014    11
    2015    13
Name: avg_package, dtype: int64

In [11]:
multi_df1['students']

cs  2012     2
    2013     4
    2014     6
ee  2012     8
    2013    10
    2014    12
    2015    14
Name: students, dtype: int64