# Multi Index DataFrame

In [1]:
import numpy as np, pandas as pd

In [6]:
multiIndVal = [('cs',2012), ('cs', 2013), ('cs', 2014), ('ee', 2012), ('ee', 2013), ('ee', 2014), ('ee', 2015)]
multiInd = pd.MultiIndex.from_tuples(multiIndVal)

In [7]:
multi_df1 = pd.DataFrame(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [9, 10],
        [11, 12],
        [13, 14],
    ],
    index = multiInd,
    columns = ['avg_package', 'students']
)

multi_df1

         avg_package  students
cs 2012            1         2
   2013            3         4
   2014            5         6
ee 2012            7         8
   2013            9        10
   2014           11        12
   2015           13        14

In [9]:
multi_df1.loc['cs']
multi_df1.loc['ee']

      avg_package  students
2012            7         8
2013            9        10
2014           11        12
2015           13        14

In [10]:
multi_df1['avg_package']

cs  2012     1
    2013     3
    2014     5
ee  2012     7
    2013     9
    2014    11
    2015    13
Name: avg_package, dtype: int64

In [11]:
multi_df1['students']

cs  2012     2
    2013     4
    2014     6
ee  2012     8
    2013    10
    2014    12
    2015    14
Name: students, dtype: int64

In [13]:
# multiindex df from columns perspective
multiindex_df2 = pd.DataFrame(
    [
        [1,2,3,2],
        [3,4,0,2],
        [5,6,2,5],
        [0,8,7,3],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['karachi','islamabad'],['avg_package','students']])
)

multiindex_df2

         karachi            islamabad
     avg_package students avg_package students
2019           1        2           3        2
2020           3        4           0        2
2021           5        6           2        5
2022           0        8           7        3

In [14]:
multiindex_df2['karachi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            0         8

In [15]:
multiindex_df2['islamabad']

      avg_package  students
2019            3         2
2020            0         2
2021            2         5
2022            7         3

In [16]:
multiindex_df2['karachi']['students']

2019    2
2020    4
2021    6
2022    8
Name: students, dtype: int64

In [17]:
multiindex_df2['islamabad']['avg_package']

2019    3
2020    0
2021    2
2022    7
Name: avg_package, dtype: int64

In [18]:
multiindex_df2.loc[2021]

karachi    avg_package    5
           students       6
islamabad  avg_package    2
           students       5
Name: 2021, dtype: int64

In [20]:
# Multiindex df in terms of both cols and index

multiindex_df3 = pd.DataFrame(
    [
        [1,2,5,2],
        [3,4,3,2],
        [5,6,7,2],
        [7,8,3,4],
        [9,10,9,10],
        [11,12,9,7],
        [8,14,8,15],
    ],
    index = multiInd,
    columns = pd.MultiIndex.from_product([['karachi','islamabad'],['avg_package','students']])
)

multiindex_df3

            karachi            islamabad
        avg_package students avg_package students
cs 2012           1        2           5        2
   2013           3        4           3        2
   2014           5        6           7        2
ee 2012           7        8           3        4
   2013           9       10           9       10
   2014          11       12           9        7
   2015           8       14           8       15

In [24]:
multiindex_df3.shape # to check the dimension of DataFrame

(7, 4)

In [ ]:
# by using multiindexing, we can easily represent higher dimension data into lower dimension object (like series or dataframe)

## Stacking and Unstacking

In [25]:
multi_df1

         avg_package  students
cs 2012            1         2
   2013            3         4
   2014            5         6
ee 2012            7         8
   2013            9        10
   2014           11        12
   2015           13        14

In [30]:
multi_df1.unstack()

   avg_package                  students
          2012 2013  2014  2015     2012  2013  2014  2015
cs         1.0  3.0   5.0   NaN      2.0   4.0   6.0   NaN
ee         7.0  9.0  11.0  13.0      8.0  10.0  12.0  14.0

In [33]:
multi_df1.unstack().unstack()

avg_package  2012  cs     1.0
                   ee     7.0
             2013  cs     3.0
                   ee     9.0
             2014  cs     5.0
                   ee    11.0
             2015  cs     NaN
                   ee    13.0
students     2012  cs     2.0
                   ee     8.0
             2013  cs     4.0
                   ee    10.0
             2014  cs     6.0
                   ee    12.0
             2015  cs     NaN
                   ee    14.0
dtype: float64