In [1]:
import numpy as np, pandas as pd

# Multiple Index Series

In [4]:
multi_index = [('cs',2019), ('se', 2010), ('ds', 2011), ('cs', 2012), ('se', 2013), ('cs', 2014), ('se', 2015)]
multi_index_series = pd.Series([5, 8, 9, 6, 7, 11, 10], index = multi_index)
multi_index_series

(cs, 2019)     5
(se, 2010)     8
(ds, 2011)     9
(cs, 2012)     6
(se, 2013)     7
(cs, 2014)    11
(se, 2015)    10
dtype: int64

In [21]:
# The problem?
multi_index_series['cs']
# We cannot fatch any data by just using multi_index_series['cs']
# because there is 2 indexes and not 1 so these 2 indexed are attatched with eachother 
# so if you want to fatch any data in this multi index series, you have to write a big code maybe.

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
# The solution ---> Multi index series (known as Hierarchical Indexing).
# Let's see how to create multi index object.

In [9]:
# How to creare multiindex object?
# 1. pd.MultiIndex.from_tuples()
multi_index = [('cs',2019), ('se', 2010), ('ds', 2011), ('cs', 2012), ('se', 2013), ('cs', 2014), ('se', 2015)]
multi_index_series = pd.MultiIndex.from_tuples(multi_index)
multi_index_series.levels[1]

Index([2010, 2011, 2012, 2013, 2014, 2015, 2019], dtype='int64')

In [12]:
# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['ai', 'ds', 'ee', 'ce'], [2019, 2020, 2021, 2022, 2023, 2024]])

MultiIndex([('ai', 2019),
            ('ai', 2020),
            ('ai', 2021),
            ('ai', 2022),
            ('ai', 2023),
            ('ai', 2024),
            ('ds', 2019),
            ('ds', 2020),
            ('ds', 2021),
            ('ds', 2022),
            ('ds', 2023),
            ('ds', 2024),
            ('ee', 2019),
            ('ee', 2020),
            ('ee', 2021),
            ('ee', 2022),
            ('ee', 2023),
            ('ee', 2024),
            ('ce', 2019),
            ('ce', 2020),
            ('ce', 2021),
            ('ce', 2022),
            ('ce', 2023),
            ('ce', 2024)],
           )

In [14]:
# Create a series with multiindex object
pd.Series([5, 4, 8, 9, 12, 11, 3], index = multi_index_series)

cs  2019     5
se  2010     4
ds  2011     8
cs  2012     9
se  2013    12
cs  2014    11
se  2015     3
dtype: int64

## Practice

In [17]:
# by using pd.MultiIndex.from_tuples()
multiIndVal = [('cs',2012), ('cs', 2013), ('cs', 2014), ('ee', 2012), ('ee', 2013), ('ee', 2014), ('ee', 2015)]
multiInd = pd.MultiIndex.from_tuples(multiIndVal)
multiIndSeries = pd.Series([5, 6, 8, 9, 10, 8, 3], index = multiInd)
multiIndSeries

cs  2012     5
    2013     6
    2014     8
ee  2012     9
    2013    10
    2014     8
    2015     3
dtype: int64

In [18]:
# by using pd.MultiIndex.from_product()
multi_indexing = pd.MultiIndex.from_product([['ai', 'ml'], [2010, 2011, 2012, 2013, 2014, 2015]])
multi_ind_series = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], index = multi_indexing)
multi_ind_series

ai  2010     1
    2011     2
    2012     3
    2013     4
    2014     5
    2015     6
ml  2010     7
    2011     8
    2012     9
    2013    10
    2014    11
    2015    12
dtype: int64

In [20]:
# How to fatch items from such series
multi_ind_series[('ai',2011)]
multi_ind_series['ml']

2010     7
2011     8
2012     9
2013    10
2014    11
2015    12
dtype: int64

In [27]:
# dimension
multi_indexing.ndim
multiIndSeries.ndim

1

In [26]:
# unstack()
multi_ind_series.unstack()

    2010  2011  2012  2013  2014  2015
ai     1     2     3     4     5     6
ml     7     8     9    10    11    12

In [29]:
temp_mis = multiIndSeries.unstack()
temp_mis

    2012  2013  2014  2015
cs   5.0   6.0   8.0   NaN
ee   9.0  10.0   8.0   3.0

In [31]:
# stack()
temp_mis.stack()

cs  2012     5.0
    2013     6.0
    2014     8.0
ee  2012     9.0
    2013    10.0
    2014     8.0
    2015     3.0
dtype: float64

In [ ]:
# Why we need Multi Index objects?
# We can easily represent higher dimensions object into the lower dimensions series and dataframe onjects.