# Merging, Joining, and Concatenating

In [2]:
import numpy as np, pandas as pd

In [4]:
courses = pd.read_csv('courses.csv')
students = pd.read_csv('students.csv')
reg_month1 = pd.read_csv('reg-month1.csv')
reg_month2 = pd.read_csv('reg-month2.csv')
matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')

#### concat()

In [20]:
#  We can vertically stack the different datasets by using concat
# pd.concat([reg_month1, reg_month2]) # but here is a problem, it repeats the indexes

# to solve the above problem, you can use ignore_index
registrations = pd.concat([reg_month1, reg_month2], ignore_index = True)
registrations

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [24]:
# if you want to differentiate among/between different datasets while keeping the indexes retain/intact.
multi_reg = pd.concat([reg_month1, reg_month2], keys = ['reg_month1', 'reg_month2'])
multi_reg

               student_id  course_id
reg_month1 0           23          1
           1           15          5
           2           18          6
           3           23          4
           4           16          9
           5           18          1
           6            1          1
           7            7          8
           8           22          3
           9           15          1
           10          19          4
           11           1          6
           12           7         10
           13          11          7
           14          13          3
           15          24          4
           16          21          1
           17          16          5
           18          23          3
           19          17          7
           20          23          6
           21          25          1
           22          19          2
           23          25         10
           24           3          3
reg_month2 0            3          5
           1           16          7
           2           12         10
           3           12          1
           4           14          9
           5            7          7
           6            7          2
           7           16          3
           8           17         10
           9           11          8
           10          14          6
           11          12          5
           12          12          7
           13          18          8
           14           1         10
           15           1          9
           16           2          5
           17           7          6
           18          22          5
           19          22          6
           20          23          9
           21          23          5
           22          14          4
           23          14          1
           24          11         10
           25          42          9
           26          50          8
           27          38          1

In [25]:
multi_reg.loc['reg_month2']

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [28]:
multi_reg.loc[('reg_month2', 8)]

student_id    17
course_id     10
Name: (reg_month2, 8), dtype: int64

In [30]:
# you can concat data horizontally 
reg = pd.concat([reg_month1, reg_month2], axis=1)
reg

    student_id  course_id  student_id  course_id
0         23.0        1.0           3          5
1         15.0        5.0          16          7
2         18.0        6.0          12         10
3         23.0        4.0          12          1
4         16.0        9.0          14          9
5         18.0        1.0           7          7
6          1.0        1.0           7          2
7          7.0        8.0          16          3
8         22.0        3.0          17         10
9         15.0        1.0          11          8
10        19.0        4.0          14          6
11         1.0        6.0          12          5
12         7.0       10.0          12          7
13        11.0        7.0          18          8
14        13.0        3.0           1         10
15        24.0        4.0           1          9
16        21.0        1.0           2          5
17        16.0        5.0           7          6
18        23.0        3.0          22          5
19        17.0        7.0          22          6
20        23.0        6.0          23          9
21        25.0        1.0          23          5
22        19.0        2.0          14          4
23        25.0       10.0          14          1
24         3.0        3.0          11         10
25         NaN        NaN          42          9
26         NaN        NaN          50          8
27         NaN        NaN          38          1

In [31]:
reg.shape

(28, 4)

In [22]:
# append() method is removed from the recent version, you can use concat() method instead.