# DataFrame Creation

In [1]:
import numpy as np
import pandas as pd

#### Using lists

In [4]:
student_data = [
    [95, 85, 10],
    [100, 98, 15],
    [120, 100, 20],
    [80, 75, 3],
    [150, 100, 25]
]

pd.DataFrame(student_data, columns=['IQ', 'Marks', 'Package'])

    IQ  Marks  Package
0   95     85       10
1  100     98       15
2  120    100       20
3   80     75        3
4  150    100       25

#### Using dicts

In [5]:
student_dict = {
    'IQ': [100, 90, 85, 50, 95],
    'Marks': [99, 95, 65, 20, 85],
    'Package': [12, 10, 8, 3, 11]
}

students = pd.DataFrame(student_dict)
students

    IQ  Marks  Package
0  100     99       12
1   90     95       10
2   85     65        8
3   50     20        3
4   95     85       11

### Using read_csv