# GroupBy Aggregate Method

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('imdb-top-1000.csv')
movies.head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

## by passing dict

In [6]:
genre = movies.groupby('Genre')
genre.sum(numeric_only = True)

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [7]:
genre.agg(
    {
        'Runtime' : 'mean',
        'IMDB_Rating' : 'mean',
        'No_of_Votes' : 'sum',
        'Gross' : 'sum',
        'Metascore' : 'min'
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

## by passing list

In [14]:
genre[movies.select_dtypes(include = 'number').columns].agg(['min', 'max', 'mean'])

          Runtime                  IMDB_Rating                No_of_Votes  \
              min  max        mean         min  max      mean         min
Genre
Action         45  321  129.046512         7.6  9.0  7.949419       25312
Adventure      88  228  134.111111         7.6  8.6  7.937500       29999
Animation      71  137   99.585366         7.6  8.6  7.930488       25229
Biography      93  209  136.022727         7.6  8.9  7.938636       27254
Comedy         68  188  112.129032         7.6  8.6  7.901290       26337
Crime          80  229  126.392523         7.6  9.2  8.016822       27712
Drama          64  242  124.737024         7.6  9.3  7.957439       25088
Family        100  115  107.500000         7.8  7.8  7.800000      178731
Fantasy        76   94   85.000000         7.9  8.1  8.000000       57428
Film-Noir     100  108  104.000000         7.8  8.1  7.966667       59556
Horror         71  122  102.090909         7.6  8.5  7.909091       27007
Mystery        96  138  119.083333         7.6  8.4  7.975000       33982
Thriller      108  108  108.000000         7.8  7.8  7.800000       27733
Western       132  165  148.250000         7.8  8.8  8.350000       65659

                                         Gross                             \
               max           mean          min          max          mean
Genre
Action     2303232  420246.581395       3296.0  936662225.0  1.897224e+08
Adventure  1512360  313557.819444      61001.0  874211619.0  1.319017e+08
Animation   999790  268032.073171     128985.0  873839108.0  1.784326e+08
Biography  1213505  272805.045455      21877.0  753585104.0  9.404952e+07
Comedy      939631  178195.658065       1305.0  886752933.0  1.010572e+08
Crime      1826188  313398.271028       6013.0  790482117.0  7.899656e+07
Drama      2343110  212343.612457       3600.0  924558264.0  1.225259e+08
Family      372490  275610.500000    4000000.0  435110554.0  2.195553e+08
Fantasy      88794   73111.000000  337574718.0  445151978.0  3.913633e+08
Film-Noir   158731  122405.000000     449191.0  123353292.0  4.197018e+07
Horror      787806  340232.363636      89029.0  298791505.0  9.405902e+07
Mystery    1129894  350250.333333    1035953.0  474203697.0  1.047014e+08
Thriller     27733   27733.000000   17550741.0   17550741.0  1.755074e+07
Western     688390  322416.250000    5321508.0   31800000.0  1.455538e+07

          Metascore
                min    max       mean
Genre
Action         33.0   98.0  73.419580
Adventure      41.0  100.0  78.437500
Animation      61.0   96.0  81.093333
Biography      48.0   97.0  76.240506
Comedy         45.0   99.0  78.720000
Crime          47.0  100.0  77.080460
Drama          28.0  100.0  79.701245
Family         67.0   91.0  79.000000
Fantasy         NaN    NaN        NaN
Film-Noir      94.0   97.0  95.666667
Horror         46.0   97.0  80.000000
Mystery        52.0  100.0  79.125000
Thriller       81.0   81.0  81.000000
Western        69.0   90.0  78.250000

In [17]:
# another way
genre[['Runtime', 'IMDB_Rating', 'No_of_Votes', 'Gross', 'Metascore']].agg(['min', 'max', 'mean', 'sum'])

          Runtime                         IMDB_Rating                         \
              min  max        mean    sum         min  max      mean     sum
Genre
Action         45  321  129.046512  22196         7.6  9.0  7.949419  1367.3
Adventure      88  228  134.111111   9656         7.6  8.6  7.937500   571.5
Animation      71  137   99.585366   8166         7.6  8.6  7.930488   650.3
Biography      93  209  136.022727  11970         7.6  8.9  7.938636   698.6
Comedy         68  188  112.129032  17380         7.6  8.6  7.901290  1224.7
Crime          80  229  126.392523  13524         7.6  9.2  8.016822   857.8
Drama          64  242  124.737024  36049         7.6  9.3  7.957439  2299.7
Family        100  115  107.500000    215         7.8  7.8  7.800000    15.6
Fantasy        76   94   85.000000    170         7.9  8.1  8.000000    16.0
Film-Noir     100  108  104.000000    312         7.8  8.1  7.966667    23.9
Horror         71  122  102.090909   1123         7.6  8.5  7.909091    87.0
Mystery        96  138  119.083333   1429         7.6  8.4  7.975000    95.7
Thriller      108  108  108.000000    108         7.8  7.8  7.800000     7.8
Western       132  165  148.250000    593         7.8  8.8  8.350000    33.4

          No_of_Votes                                          Gross  \
                  min      max           mean       sum          min
Genre
Action          25312  2303232  420246.581395  72282412       3296.0
Adventure       29999  1512360  313557.819444  22576163      61001.0
Animation       25229   999790  268032.073171  21978630     128985.0
Biography       27254  1213505  272805.045455  24006844      21877.0
Comedy          26337   939631  178195.658065  27620327       1305.0
Crime           27712  1826188  313398.271028  33533615       6013.0
Drama           25088  2343110  212343.612457  61367304       3600.0
Family         178731   372490  275610.500000    551221    4000000.0
Fantasy         57428    88794   73111.000000    146222  337574718.0
Film-Noir       59556   158731  122405.000000    367215     449191.0
Horror          27007   787806  340232.363636   3742556      89029.0
Mystery         33982  1129894  350250.333333   4203004    1035953.0
Thriller        27733    27733   27733.000000     27733   17550741.0
Western         65659   688390  322416.250000   1289665    5321508.0

                                                   Metascore         \
                   max          mean           sum       min    max
Genre
Action     936662225.0  1.897224e+08  3.263226e+10      33.0   98.0
Adventure  874211619.0  1.319017e+08  9.496922e+09      41.0  100.0
Animation  873839108.0  1.784326e+08  1.463147e+10      61.0   96.0
Biography  753585104.0  9.404952e+07  8.276358e+09      48.0   97.0
Comedy     886752933.0  1.010572e+08  1.566387e+10      45.0   99.0
Crime      790482117.0  7.899656e+07  8.452632e+09      47.0  100.0
Drama      924558264.0  1.225259e+08  3.540997e+10      28.0  100.0
Family     435110554.0  2.195553e+08  4.391106e+08      67.0   91.0
Fantasy    445151978.0  3.913633e+08  7.827267e+08       NaN    NaN
Film-Noir  123353292.0  4.197018e+07  1.259105e+08      94.0   97.0
Horror     298791505.0  9.405902e+07  1.034649e+09      46.0   97.0
Mystery    474203697.0  1.047014e+08  1.256417e+09      52.0  100.0
Thriller    17550741.0  1.755074e+07  1.755074e+07      81.0   81.0
Western     31800000.0  1.455538e+07  5.822151e+07      69.0   90.0


                mean      sum
Genre
Action     73.419580  10499.0
Adventure  78.437500   5020.0
Animation  81.093333   6082.0
Biography  76.240506   6023.0
Comedy     78.720000   9840.0
Crime      77.080460   6706.0
Drama      79.701245  19208.0
Family     79.000000    158.0
Fantasy          NaN      0.0
Film-Noir  95.666667    287.0
Horror     80.000000    880.0
Mystery    79.125000    633.0
Thriller   81.000000     81.0
Western    78.250000    313.0

## adding both the syntax

In [18]:
genre.agg(
    {
        'Runtime' : ['mean', 'min'],
        'IMDB_Rating' : ['mean', 'max'],
        'No_of_Votes' : ['sum', 'mean'],
        'Gross' : 'sum',
        'Metascore' : ['min', 'mean']
    }
)

              Runtime      IMDB_Rating      No_of_Votes                 \
                 mean  min        mean  max         sum           mean
Genre
Action     129.046512   45    7.949419  9.0    72282412  420246.581395
Adventure  134.111111   88    7.937500  8.6    22576163  313557.819444
Animation   99.585366   71    7.930488  8.6    21978630  268032.073171
Biography  136.022727   93    7.938636  8.9    24006844  272805.045455
Comedy     112.129032   68    7.901290  8.6    27620327  178195.658065
Crime      126.392523   80    8.016822  9.2    33533615  313398.271028
Drama      124.737024   64    7.957439  9.3    61367304  212343.612457
Family     107.500000  100    7.800000  7.8      551221  275610.500000
Fantasy     85.000000   76    8.000000  8.1      146222   73111.000000
Film-Noir  104.000000  100    7.966667  8.1      367215  122405.000000
Horror     102.090909   71    7.909091  8.5     3742556  340232.363636
Mystery    119.083333   96    7.975000  8.4     4203004  350250.333333
Thriller   108.000000  108    7.800000  7.8       27733   27733.000000
Western    148.250000  132    8.350000  8.8     1289665  322416.250000

                  Gross Metascore
                    sum       min       mean
Genre
Action     3.263226e+10      33.0  73.419580
Adventure  9.496922e+09      41.0  78.437500
Animation  1.463147e+10      61.0  81.093333
Biography  8.276358e+09      48.0  76.240506
Comedy     1.566387e+10      45.0  78.720000
Crime      8.452632e+09      47.0  77.080460
Drama      3.540997e+10      28.0  79.701245
Family     4.391106e+08      67.0  79.000000
Fantasy    7.827267e+08       NaN        NaN
Film-Noir  1.259105e+08      94.0  95.666667
Horror     1.034649e+09      46.0  80.000000
Mystery    1.256417e+09      52.0  79.125000
Thriller   1.755074e+07      81.0  81.000000
Western    5.822151e+07      69.0  78.250000